FROM python:3.12-slim

WORKDIR /app_server

COPY src/api/requirements.txt .

RUN pip3 install -r requirements.txt

COPY src/api/v2/main.py .
COPY model/model.joblib .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]