events {
    # Maximum number of connections per process
    worker_connections 1024; 
}

http {
    # Rate limiting zone: 10 requests per second per client
    limit_req_zone $binary_remote_addr zone=apilimit:10m rate=10r/s;

    # Upstream block (load balancing) for api-v1
    upstream v1-apis {
        server api-v1:8000;
    }

    # Upstream block for api-v2
    upstream v2-apis {
        server api-v2:8000;
    }

    # A/B Testing: Map "X-Experiment-Group=debug" to api-v2
    map $http_x_experiment_group $backend {
        default http://v1-apis;
        debug   http://v2-apis;
    }
    
    # HTTP server
    server {
        # Listen on port 80
        listen 80;
        # Domain name or IP that server block manages
        server_name localhost;
        # Redirects all HTTP requests to HTTPS
        return 301 https://$host$request_uri;
    }
    
    # HTTPS server
    server {
        # Listen on port 443 and enable SSL
        listen 443 ssl; 
        # Domain name or IP that server block manages
        server_name localhost; 

        # Paths to SSL certificates inside the Nginx container
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        # SSL protocols and ciphers
        ssl_protocols TLSv1.2 TLSv1.3; # Only allow modern versions of TLS
        ssl_ciphers HIGH:!aNULL:!MD5; # List of allowed cipher suites
        ssl_prefer_server_ciphers on; # Prefer server ciphers

        # Predict endpoint
        location /predict {
            # Enabling HTTP Basic Authentication
            auth_basic "API Access Protected";
            # Path to the .htpasswd file in the container
            auth_basic_user_file /etc/nginx/.htpasswd; 

            # Applies the limitation to the `location/predict` block
            limit_req zone=apilimit burst=5 nodelay;

            # Reverse proxy to backend (chosen by A/B Testing mapping)
            proxy_pass $backend;

            # Forward headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Nginx status endpoint
        location /nginx_status {
            stub_status on; # Enables the stub_status module
            access_log off; # Do not log access to this endpoint
            allow 127.0.0.1; # Allow access only from localhost (export it)
            allow 172.18.0.0/16; # Or from the Docker network
            deny all; # Blocks all other access
        }

    }
}